//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRIKprooviülesanne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osavotjad
    {
        public int ID { get; set; }
        public string Eesnimi { get; set; }
        public string Perenimi { get; set; }
        public int Isikukood { get; set; }
        public string Makskmisviis { get; set; }
        public string Lisainfo { get; set; }
        public Nullable<int> Yritus_ID { get; set; }
    
        public virtual Yritus1 Yritus1 { get; set; }
    }
}
