//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRIKprooviülesanne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yritus1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yritus1()
        {
            this.Osavotjads = new HashSet<Osavotjad>();
        }
    
        public int ID { get; set; }
        public string Ürituse_nimi { get; set; }
        public System.DateTime Toimumisaeg { get; set; }
        public string Koht { get; set; }
        public string Lisainfo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Osavotjad> Osavotjads { get; set; }
    }
}
